---
- name: Download alertmanager
  get_url:
    url: "{{ alert_url }}"
    dest: "{{ alert_dest }}"
- name: Extract alertmanager
  unarchive:
    src: "{{ alert_dest }}"
    dest: "{{ alert_install_dir }}"
    extra_opts: "--strip-components=1"
    remote_src: yes
- name: Copy alertmanager binaries
  copy:
    src: "{{ alert_install_dir }}/{{ item }}"
    dest: /usr/local/bin
    owner: alertmanager
    group: alertmanager
    remote_src: yes
    mode: 0755
  with_items:
    - alertmanager
    - amtool
- name: Copy alertmanager.yml file from src to dest
  template:
    src: templates/alertmanager.yml.j2
    dest: /etc/alertmanager/alertmanager.yml
    owner: alertmanager
    group: alertmanage
    remote_src: yes
    mode: 0755
- name: copy alertmanager service file
  template:
    src: templates/alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
- name: start alertmanager service
  service:
    daemon_reload: yes
    name: alertmanager
    state: started
    enabled: yes
  when: ansible_service_mgr == "systemd"

