---
- name: Download node exporter
  get_url:
    url: "{{ node_exp_url }}"
    dest: "{{ node_exp_dest }}"
- name: Extract node exporter
  unarchive: 
    src: "{{ node_exp_dest }}"
    dest: "{{ node_exp_install_dir }}"
    extra_opts: "--strip-components=1"
- name: Copy node exporter binaries
  copy:
    src: "{{ node_exp_install_dir }}/node_exporter" 
    dest: /usr/local/bin
    owner: node_exporter
    group: node_exporter
    mode: 0755
- name: copy node exporter service file
  template:
    src: templates/node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
- name: start node_exporter service
  service:
    daemon_reload: yes
    name: node_exporter
    state: started
    enabled: yes
    when: ansible_service_mgr == "systemd"

