---
- name: Install Basic Packages
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - apt-transport-https
    - software-properties-common   
- name: Adding key for Grafana
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
- name: Adding repository for Grafana
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
- name: Update 
  apt:
    update_cache: yes    
- name: Install Grafana
  apt:
    name: grafana
    update_cache: yes  
- name: Start and enable Grafana
  service:
    daemon_reload: yes
    name: grafana-server
    state: started
    enabled: yes
  when: ansible_service_mgr == "systemd"  
