---
- name: 
- name: copy node exporter service file
  template:
    src: templates/node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
- name: start node_exporter service
  service:
    daemon_reload: yes
    name: node_exporter
    state: started
    enabled: yes
    when: ansible_service_mgr == "systemd"

