---
- name: Download Prometheus
  get_url:
    url: "{{ prom_archive_url }}"
    dest: "{{ prom_archive_dest }}"
- name: Extract Prometheus
  unarchive: 
    src: "{{ prom_archive_dest }}"
    dest: "{{ prom_install_dir }}"
    extra_opts: "--strip-components=1"
- name: Copy prometheus binaries
  copy:
    src: "{{ prom_install_dir }}/{{ item }}" 
    dest: /usr/local/bin
    owner: prometheus
    group: prometheus
    mode: 0755
  with_items:
    - prometheus
    - promtool
- name: Copy configuration files
  copy:
    src: "{{ prom_install_dir }}/{{ item }}"
    dest: /etc/prometheus
    owner: node_exporter
    group: node_exporter
  with_items:
    - consoles
    - console_libraries
- name: Copy prometheus.yml file
  template: 
    src: templates/prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: 0755  
- name: copy prometheus service template
  template:
    src: templates/prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    #notify: restart prometheus service    
- name: Service creation  
  service:
    daemon_reload: yes
    name: prometheus
    state: started
    enabled: yes
  when: ansible_service_mgr == "systemd"  
